config/routes.rb
Science::Application.routes.draw do
  
  resources :articles, :users, :sessions
  root :to => "articles#index"
  match "feed" => "articles#feed", :as => 'feed', :defaults => { :format => 'rss' }

  match 'category/:category' => "articles#index", :as => 'articles_from_category', :constraints => { :category => /(technology|world|gadgets|cosmos)/ }

  match "admin" => "sessions#new"
  match "log_out" => "sessions#destroy"
  match 'all_articles' => 'articles#as_dict'

end

app/models/article.rb
# encoding: utf-8

class Article < ActiveRecord::Base
  belongs_to :user
  has_friendly_id :permalink, :use_slug => true
  
  default_scope :order => "articles.created_at DESC"  

  validates :title, :presence => true, :uniqueness => true
  validates :preview, :presence => true, :uniqueness => true
  validates :text, :presence => true, :uniqueness => true, :length => {:within => 10..1000000}
  validates :permalink, :presence => true, :uniqueness => true

  def self.as_dictionary
    dictionary = Hash.new {|hash, key| hash[key] = [] }
 
    Article.all.each do |p|
      dictionary[p.title[ 0]] << p
    end
 
    dictionary.sort
  end

end

app/controllers/articles_controller.rb
# encoding: utf-8

class ArticlesController < InheritedResources::Base
  before_filter :must_be_admin, :except => [:show, :index, :feed, :translit]

  def index
    @articles = Article.where(:visible => true).page(params[:page]).per(5) #pagination Kaminari
    if params[:category]
       @articles = Article.where(:category => params[:category]).page(params[:page]).per(5) #pagination Kaminari
       @title = "#{(I18n.t params[:category])} - все самое интересное"
    end
  end

  def show
    show!{@title = @article.title}
  end

  def new
    @title = "Админка - создание новой статьи"
    new! do |format| 
      format.html { render :layout => 'admin_layout' }
    end
  end

  def create
    create!(:notice => "Новая статья успешно создана и добавлена в ленту!")
  end

  def edit
    @title = "Админка - редактирование существующей статьи"
    edit! do |format|
      format.html { render layout: 'admin_layout' }
    end
  end

  def update
    update!(:notice => "Статья отредактирована успешно!")
  end

  def destroy
    destroy!(:notice => "Статья была успешно удалена")
  end

  def feed
        
    @articles = Article.where(visible: true)

    respond_to do |format|
      format.rss { render :layout => false } #index.rss.builder
    end
  end

  private

  def must_be_admin
    unless current_user
      redirect_to root_path, :alert => "Пшел вон!"
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
  <div class="field">
    <%= f.label :permalink, "Адрес урла статьи" %><br />
    <%= f.text_field :permalink, :size => "61" %><br /><br />
  </div>
  <div class="field">
    <%= f.label :title, "Здесь тайтл, он же h1" %><br />
    <%= f.text_field :title, :size => "61" %><br /><br />
  </div>
  <div class="field">
    <%= f.label :preview, "То, что будет во введении" %><br />
    <%= f.text_area :preview, :size => "80x10" %><br /><br />
  </div>
  <div class="field">
    <%= f.label :text, "ВСЯ статья целиком, ВКЛЮЧАЯ введение!" %><br />
    <%= f.text_area :text, :size => "80x20" %><br /><br />
  </div>
  <div class="field">
    <%= f.label :category, "Без категории статью НЕ создавай" %>
    <%= f.select :category, options_for_select(["technology", "world", "gadgets", "cosmos"], @article.category) %>
  </div>
  <div class="field">
    <%= f.label :visible, "Видна ли на главной? Кликни, ЕСЛИ видна" %>
    <%= f.check_box :visible  %>
  </div>
  <div class="field">
    <%= f.label :sidebar_visible, "Видна ли в Последних статьях?" %>
    <%= f.check_box :sidebar_visible %>
  </div>

app/views/articles/as_dict.html.haml
- Article.as_dictionary.each do |letter, list|
  %p
    %strong= letter
  %ul
  - list.each do |post|
    %li= link_to post.title, post

app/views/articles/edit.html.erb
<div id="admin_form">

<%= link_to "<< к редактируемой статье", article_path(@article) %>

<h1>Редактирование статьи</h1>

<%= form_for @article do |f| %>

  <%= render(:partial => "form", :locals => {:f => f}) %>  

  <div class="form_action">
    <%= f.submit "СОХРАНИТЬ" %>
  </div>
<% end %>

</div>

<%= render 'layouts/admin_info' %>

app/views/articles/index.html.erb
  <div id="leftc">  
    <% @articles.each do |article| %>
      <div class="article">
        <div class="entry">
          <h2><%= link_to("#{article.title}", article_path(article)) %></h2>
            <div class="article_time"><p> Опубликовано <font color="#055DAE"><%= I18n.l article.created_at, :formats => :default %>
            </font></p></div>
          <%= raw RedCloth.new(article.preview).to_html %>

              <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir"></div>

        </div>  
      </div>
    <% end %>
    <div id="pagination">
      <%= paginate @articles %>
    </div>
  </div>

app/views/articles/new.html.erb
<%# New action has an admin layout %>

<div id="admin_form">

<%= link_to "<< на главную", root_path %>

<h1>Создание новой статьи</h1>

<%= form_for @article do |f| %>
  <%= render "shared/error_messages" %>
  <%= render(:partial => "form", :locals => {:f => f}) %>

  <div class="form_action">
    <%= f.submit "СОХРАНИТЬ" %>
  </div>
<% end %>

</div>

<%= render 'layouts/admin_info' %>

app/views/articles/show.html.erb
<div id="leftc">
  <div class="article">
    <div class="inner-entry">
      <h1><%= @article.title %></h1>
        <div class="article_time">
          <p> Опубликовано <font color="#055DAE"><%= I18n.l @article.created_at, :formats => :default %></font></p>
        </div>
        <p><%= raw  RedCloth.new(@article.text).to_html %></p>
        <% if current_user %>
          <p> <%= link_to("delete", @article, :method => :delete, :confirm => "Are you sure?") if current_user.admin? %>
          <%= link_to("edit", edit_article_path(@article)) if current_user.admin? %> </p>
        <% end %>
<div style="display:inline-block;">
<table>
  <tbody>
    <tr>
          <td width="400px"><div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj"></div> </td>

          <td><div id="vk_like"></div>
<script type="text/javascript">
VK.Widgets.Like("vk_like", {type: "mini"});
</script></td>

          <td><div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=176127499111477&amp;xfbml=1"></script><fb:like href="http://scione.ru" send="false" layout="button_count" show_faces="false" font="tahoma"></fb:like></td>
      
      </tr>
    </tbody>
  </table>
    
</div>
        
        <!-- End of Vkontakte comments API -->
        <h3>Комментарии:</h3>
        <div id="vk_comments"></div>
          <script type="text/javascript">
            VK.Widgets.Comments("vk_comments", {limit: 10, width: "600", attach: "*"});
          </script>
        <!-- The end of Vkontakte comments API -->
    </div>
  </div>
</div>