config/routes.rb
Science::Application.routes.draw do
  
  resources :articles, :users, :sessions
  root :to => "articles#index"
  match "feed" => "articles#feed", :as => 'feed', :defaults => { :format => 'rss' }

  match 'category/:category' => "articles#index", :as => 'articles_from_category', :constraints => { :category => /(technology|world|gadgets|cosmos)/ }

  match "admin" => "sessions#new"
  match "log_out" => "sessions#destroy"
  match 'all_articles' => 'articles#as_dict'

end

app/views/layouts/_admin_info.html.erb
<div id="admin_help">

  <h2>FAQ под админке</h2>
  <ul>
    <li>!{Width:525px}картинка!</li>
    <li>*<strong>жирный текст</strong>*</li>
    <li>_<i>подчеркнутый текст</i>_</li>
    <li>*маркированый список 1<br />
        *маркированый список 2</li>
    <li>#нумерованый список 1</li>
    <li>Сcылка: "текст ссылки":http://адрес-ссылки.org</link>
  </ul>

</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="left" id="footer-left">
	  <p class="large">&copy; 2011 SciOne.ru Наука о новостях</p>
  </div>
	<div class="right" id="footer-right">
	  <p class="large">
      <%= link_to "Технологии", articles_from_category_path('technology') %> <span class="text-separator">|</span> 
      <%= link_to "Гаджеты", articles_from_category_path('gadgets') %> <span class="text-separator">|</span> 
      <%= link_to "Космос", articles_from_category_path('cosmos') %><span class="text-separator">|</span> 
      <%= link_to "Мир", articles_from_category_path('world') %>
      <a href="#">&uarr;</a>
    </p> 
	</div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <a href="/"><div id="logo">
  </div></a>
  <div class="nav">
    <% if current_user %>
      <ul>
        <li><b><%= Article.count %></b> статей в базе </li> -
        <li><%= link_to "Все статьи", all_articles_path %></li> |
        <li>logged in as <strong><%= current_user.username %></strong></li> |
        <li><%= link_to "На главную", articles_path %> |
        <li><%= link_to("Добавить новую статью", new_article_path) %></li> |
        <li><%= link_to "Sign out", log_out_path, :method => :delete %></li>
      </ul>
    <% end %>
  </div>
</div>
<div id="categories">
  <div id="themes">
    <%= link_to image_tag("rss-icon.png", :size => "25x25", :align => "right"), 'http://feeds.feedburner.com/scione' %>
    <ul class="main-menu">
      <li<%= put_class('technology') %>><%= link_to "ТЕХНОЛОГИИ", articles_from_category_path('technology') %><span></span></li>
      <li<%= put_class('gadgets') %>><%= link_to "ГАДЖЕТЫ", articles_from_category_path('gadgets') %><span></span></li>
      <li<%= put_class('cosmos') %>><%= link_to "КОСМОС", articles_from_category_path('cosmos') %><span></span></li>
      <li<%= put_class('world') %>><%= link_to "МИР", articles_from_category_path('world') %><span></span></li>
    </ul>
  </div>
</div>

app/views/layouts/_sidebar.html.haml
#sidebar
 %h2 
  Последние статьи 
  =put_sidebar_category
 %ul
  -@sidebar_offers.each do |article|
   %li
    = link_to article.title, article_path(article)
   %hr
 %h2 
  Самое популярное
  %ul
   %li
    %a(href="http://scione.ru/articles/darvaza-turkmenistan-dver-v-ad") Дарваза, Туркменистан - "дверь в ад"
   %hr
   %li
    %a(href="http://scione.ru/articles/last-science-figures-out-keys-sexy-dancing") Учёные наконец подобрали ключ к разгадке феномена «Сексуального танца»
   %hr
   %li
    %a(href="http://scione.ru/articles/best-2011-our-favorite-products-future") Лучшее с Международной Выставки Потребительской Электроники 2011: наши любимые гаджеты будущего
   %hr
   %li
    %a(href="http://scione.ru/articles/sposobny-li-uchenye-sozdat-virus-prevrawajuwij-ljudej-v-zombi") Способны ли ученые создать вирус, превращающий людей в зомби?
   %hr
   %li
    %a(href="http://scione.ru/articles/roboty-v-processe-jevoljucii-projavljajut-altruizm") Роботы в процессе эволюции проявляют альтруизм
   %hr
   %li
    %a(href="http://scione.ru/articles/samsung7-sliding-netbook") Лучшее с МВПЭ 2011: "Планшетный ноутбук" Samsung
   %hr
   %li
    %a(href="http://scione.ru/articles/pomdevices-sonamba-wellbeing-monitor") Лучшее с МВПЭ 2011: беби-ситтер для бабушки ;)
   %hr
   %li
    %a(href="http://scione.ru/articles/ecoupled-wireless-charging-tesla-car") Лучшее с МВПЭ 2011: заряжаемый eMobil
   %hr
   %li
    %a(href="http://scione.ru/articles/marsohod-spirit-peredal-poslednij-snimok-s-marsa") Марсоход Спирит передал последний снимок с Марса
   %hr
   %li
    %a(href="http://scione.ru/articles/%D0%BEtlichnoe-video-vnutrennjaja-zhizn-kletki") Отличное видео – внутренняя жизнь клетки
   %hr

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'style', :media => 'screen' %>
<script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
<%= auto_discovery_link_tag(:rss, "http://scione.ru/feed") %>

  <!--Vkontakte comments API -->
    <script type="text/javascript" src="http://userapi.com/js/api/openapi.js?29"></script>

    <script type="text/javascript">
      VK.init({apiId: 2304429, onlyWidgets: true});
    </script>
  <!-- The end of Vkontakte comments API -->

  <!--Vkontakte Interesno API -->
    <script type="text/javascript" src="http://userapi.com/js/api/openapi.js?26"></script>

    <script type="text/javascript">
      VK.init({apiId: 2304429, onlyWidgets: true});
    </script>
  <!-- The end of Vkontakte Interesno API -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12858148-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<link rel="shortcut icon" href="/favicon.ico" />

<meta name='yandex-verification' content='5832b61dd6c3d73f' />

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <%= csrf_meta_tag %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.js" %>
  <%= javascript_include_tag "rails" %>
  <%= javascript_include_tag "jquery.synctranslit" %>
  <%= stylesheet_link_tag "admin" %>
  <script type="text/javascript">
    $(document).ready(function(){
      $("li").hover(function(){
        $(this).toggleClass("highlight"); 
      });
    });
  </script>

  <script type="text/javascript">
    $(document).ready(function(){
        $("#article_title").syncTranslit({destination: "article_permalink"});
    });    
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <%= csrf_meta_tag %>
  <%= javascript_include_tag :defaults %>
  <%= render 'layouts/stylesheets' %>  
</head>
<body>
<!--[if lt IE 7]> <div style=' clear: both; height: 59px; padding:0 0 0 15px; position: relative;'> <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com/images/upgrade.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div> <![endif]-->

<div class="container">
  <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"> <%= value %> </div>
    <% end %>
    <div id="content">
      <div id="top-middle">
      </div>
        <%= yield %>
        <% if controller_name == 'articles' and %w(index show).include?(action_name) %> 
          <%= render 'layouts/sidebar' %>
        <% end %>
    </div>

</div> 
    <%= render 'layouts/footer' %>
    <%= @sape.links(3) %>      
 
</body>
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <%= csrf_meta_tag %>
  <%= javascript_include_tag :defaults %>
  <%= stylesheet_link_tag "login" %>
</head>
<body>

  <div id="login_page">

    <% flash.each do |key, value| %>
      <div class="flash_<%= key %>"> <%= value %> </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>